### PR TITLE
 Fix config provider composer entry

### PR DESCRIPTION
**Pull request by geerteltink**
Fixes zendframework/zend-expressive-skeleton#208

### CODE REVIEW

**Comment by michalbundyra** [comment]
`composer.lock` should be also updated, `content-hash` will be different. Please run `composer update nothing` and push changed `composer.lock` file.

**Comment by geerteltink** [comment]
@webimpress Thanx, just in time :D

**Comment by geerteltink** [comment]
We should add checks to make sure the lock file is up to date :)

**Comment by weierophinney** [comment]
@xtreamwayz Make sure you update the skeleton's installer configuration to reflect the new alpha version as well! :smile:

**Pull request merged**
