### PR TITLE
upgrade versions and fix test

### PR DESCRIPTION
**Pull request by gabbydgab**
Bumped versions to:

"zendframework/zend-expressive-router": "^1.2",
"zendframework/zend-router": "^3.0",
"zendframework/zend-psr7bridge": "^0.2.2"

### CODE REVIEW

**Comment by remicollet** [comment]
+1 as it seems very strange to see Expressive enlighted in ZF3 release notes, but only compatible with ZF2...

**Comment by fadoe** [comment]
+1

**Comment by mihailgoosbg** [comment]
+1
Any idea when can we expect this pull request to be merged with base branch ?

**Comment by fadoe** [comment]
@weierophinney Any updates on this? Is this lib maintained?

**Comment by pdrosos** [comment]
+1
@weierophinney 
Please merge this one, because it causes conflicts in composer dependencies and prevents us from using other libraries, compatible with ZF3 and its packages.

**Comment by weierophinney** [comment]
Thanks for the update; merged to develop for release with 1.2.0.

**Pull request merged**
